### ISSUE TITLE
why  npm install mongoose-findorcreate failed

### ISSUE THREAD

**Issue by oliviertech212** [drudge/mongoose-findorcreate#33]
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/mongoose-findorcreate failed, reason: getaddrinfo ENOTFOUND domain
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tech/.npm/_logs/2022-09-25T17_28_35_196Z-debug-0.log

**Comment by binki** [comment]
@oliviertech212 You need to check your internet connection. Are you able to install any other packages from npmjs?

This is not a problem with mongoose-findorcreate. It is a general problem in accessing the npmjs repository.
