### ISSUE TITLE
Not Compatible with the upcoming mongoose 7.0

### ISSUE THREAD

**Issue by hasezoey** [drudge/mongoose-findorcreate#34]
This Plugin will not be compatible with the upcoming mongoose 7.0, because:

- this plugin makes use of `self.base.Promise`, which has been removed, [see this line](https://github.com/drudge/mongoose-findorcreate/blob/master/index.js#L11)
- this plugin makes use of callbacks, which have been removed, [see this line](https://github.com/drudge/mongoose-findorcreate/blob/master/index.js#L25) or [this line](https://github.com/drudge/mongoose-findorcreate/blob/master/index.js#L38)

**Comment by drudge** [comment]
Thanks @hasezoey. Version 4.0 supports Mongoose v7.
