### ISSUE TITLE
undefined ES6

### ISSUE THREAD

**Issue by Sagayaraj8939** [drudge/mongoose-findorcreate#37]
TypeError: Cannot read properties of undefined (reading 'ES6')
    at Function.findOrCreate (C:\Users\sagayaraj.s\desktop\desktop1\Secret - Starting Code\node_modules\mongoose-findorcreate\index.js:11:37)
please define ES6 and fix the code

**Comment by binki** [comment]
It looks like you found a solution in https://github.com/drudge/mongoose-findorcreate/issues/27#issuecomment-1488077018 . Please reopen if you still have this problem with mongoose-findorcreate-4.0.0
